site_name: Hygraph_Insert

theme:
  name: material
     
  palette:
    scheme: slate
    primary: teal
    accent: light blue

  icon:
    logo: material/network
    favicon: material/Hygraph_Insert

  features:
    - content.tabs.link
    - navigation.tabs
    - toc.integrate

nav:
  - Home:
    - Home: index.md
  - Insert Data:
    - Insert Data: Insert/data_insert.md
      

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kunal-khairnar-05
      name: Kunal Khairnar


markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true